### ISSUE TITLE
dab repo entrypoint should not delete existing script unless forced

### ISSUE THREAD

**Issue by petranidis** [Nekroze/dab#77]
**Describe the bug**
dab repo entrypoint should not delete existing script unless forced

**To Reproduce**
Run dab repo entrypoint create with existing start and stop scripts

**Expected behavior**
The existing script should not be overridden by the default scripts

**Screenshots**

**`dab version` output:**

```bash
```

**Additional context**

**Comment by Nekroze** [comment]
thanks for filing a bug report.

At present `dab repo entrypoint create` already checks that the file does not exist first https://github.com/Nekroze/dab/blob/b63e4c5687c4ddf1baabb1bc059f07211cfe8e05/app/subcommands/repo/entrypoint/create.sh#L37

I have just tested this functionality and it does display the expected behavior from what I can see. May I ask what filesystem you are using?

I am doing some bug fixes anyways so I will attempt to make the file check that exists a bit more broad as well.

**Comment by Nekroze** [comment]
This should be improved/fixed in the latest version. If this issue persists please do not hesitate to reopen this issue.
